name: CI/CD

on:
  push:
    branches:
      - master
      - alpha
      - beta

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install and test
        run: yarn install && npx lerna run test
      - name: Build
        run: npx lerna run dist
      - name: Deploy to registry
        run: npx lerna run semantic-release:dry-run
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
