name: Publish to NPM

on:
  push:
    branches:
      - master
      - alpha
      - beta

jobs:
  build-n-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup GIT credentials
        run: |
          git config user.name $GITHUB_ACTOR
          git config user.email avizcaino@uxland.es
      - name: Install and test
        run: yarn install && yarn test
      - name: Build
        run: yarn build && yarn readme:coverage
      - name: Publish
        if: github.ref == 'refs/heads/alpha'
        run: npx lerna publish --conventional-commits --conventional-prerelease --yes
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
