name: CI/CD

on:
  push:
    branches:
      - master
      - alpha
      - beta

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install and test
        run: yarn install && yarn test
      - name: Build
        run: yarn build && yarn readme:coverage
  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    if: contains(github.ref, "alpha")
    steps:
      - name: Publish
        run: lerna publish --conventional-commits --conventional-prerelease --yes
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
